### ISSUE TITLE
geospatial indexing / more granular location queries

### ISSUE THREAD

**Issue by kgdiem** [chrisjm/openbrewerydb-rails-api#15]
It’d be great to have the ability to search by location. 

eg, [url]?by_location=34.3,76.5

I’d be happy to take up this issue

**Comment by chrisjm** [comment]
@kgdiem Sounds like a great feature. Feel free to tackle it. Let me know if you need anything from me.

**Comment by kgdiem** [comment]
Great. Looking forward to it.

**Comment by schevalia** [comment]
Just noticed this bug. This is something I could greatly use for the RN app I'm currently working on to utilize Chris' API. I'll see if I can take a dive into this and figure it out.

**Comment by chrisjm** [comment]
I've been looking at [PostGIS](https://postgis.net/) recently as a possible solution for this.

**Pros**
- Write location queries in SQL
- Extends PostgreSQL so should be fairly fast
- Able to update AWS so no need to change DB providers

**Cons**
- Complicates the DB setup process for local development
- A bit of a learning curve for those of us not up-to-speed on GIS (Geographic Information Systems)

Any thoughts?

**Comment by schevalia** [comment]
Still been learning the very basics of how projects like this are set up, so I don't have enough info for in-depth comparison, but I can start looking more into PostGIS. Am hoping to get a pull request submitted today for a few very minor changes.

**Comment by chrisjm** [comment]
PostGIS on RDS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.PostGIS

**Comment by ecographical** [comment]
> 
> 
> I've been looking at [PostGIS](https://postgis.net/) recently as a possible solution for this.
> 
> **Pros**
> 
>     * Write location queries in SQL
> 
>     * Extends PostgreSQL so should be fairly fast
> 
>     * Able to update AWS so no need to change DB providers
> 
> 
> **Cons**
> 
>     * Complicates the DB setup process for local development
> 
>     * A bit of a learning curve for those of us not up-to-speed on GIS (Geographic Information Systems)
> 
> 
> Any thoughts?

This is the way to go IMO. Should be simple to implement as you are only dealing with Point data correct? Returning GeoJSON, KML or just lat/long would be achieved with this.

**Comment by chrisjm** [comment]
Fixed by #58 

Though this doesn't fully address all of the different geo features, the above PR fixes the original issue (i.e., sort by distance from the coordinates).
