### ISSUE TITLE
Incorrect search for multiple words (underscores)

### ISSUE THREAD

**Issue by vshagur** [chrisjm/openbrewerydb-rails-api#41]
# Bug Report

## Describe the bug

From the [documentation for search queries](https://www.openbrewerydb.org/documentation/03-search) - _**"Note: For the query parameter, you can use underscores or url encoding for spaces."**_  Any query for multiple words (underscores are used as a separator) returns an empty dictionary.

## Steps to reproduce bug

1. We make a request to api (use underscore) - [https://api.openbrewerydb.org/breweries/search?query=san_brewery](https://api.openbrewerydb.org/breweries/search?query=san_brewery)
2. Server sends an empty response - [screenshot](https://ibb.co/y8Tq1jf)
3. We make an API request with the same parameters (use url encoding) - [https://api.openbrewerydb.org/breweries/search?query=san%20brewery](https://api.openbrewerydb.org/breweries/search?query=san%20brewery)
4. Server sends response - [screenshot](https://ibb.co/pvWdcwD)

### Expected behavior

It was expected that search results do not depend on which separator is used.

## Screenshots
[The request is made from the console.](https://ibb.co/6rvp4YN)

### Desktop

- OS: [Linux Samsung 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux]
- Browser [chromium]
- Version [Версия 73.0.3683.75 (Сборка для разработчиков), built on Debian 9.8, running on Debian 9.11 (64 бит)]

## Smartphone

None

## Additional context

We get a similar behavior when we use an autocomplete request.  

For example - 

[https://api.openbrewerydb.org/breweries/autocomplete?query=the_brewery](https://api.openbrewerydb.org/breweries/autocomplete?query=the_brewery)

[https://api.openbrewerydb.org/breweries/autocomplete?query=the%20brewery](https://api.openbrewerydb.org/breweries/autocomplete?query=the%20brewery)

**Comment by vshagur** [comment]
I noticed one more nuance. If you use a comma as a separator, the query returns data. 
For example -

[https://api.openbrewerydb.org/breweries/search?query=san,brewery](https://api.openbrewerydb.org/breweries/search?query=san,brewery)

**Comment by chrisjm** [comment]
Fixed by #60
